from pathlib import Path
import json,hashlib,gzip,io,shutil
b=Path('/tmp/dystrail-retune-2026-09-13');d=json.loads((b/'trace-rm-activity-findings.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
lines=['# Resource Manager Activity-settlement diagnosis','', 'The two Resource Manager regressions reflect real timing changes. **No ledger reset, lost earned mileage, or free stationary-action movement was observed.** The same illness events now become visible before the camp decision, so the unchanged policy rests immediately instead of first driving an hour. Additional activity/hearing time accounts for the other newly stationary days.', '', '## Parity and scope','', '- Before source: `pace-crossing-health038-source`; after source: `pace-crossing-health038-activity-source`. Exactly the previously measured source variants were copied, with identical test-only instrumentation in two tester modules and no existing lines removed or changed.', '- Both immutable reference replays match all 48 fields in all 16 original campaign rows for the two numeric seeds. Both instrumented traces independently match all 48 fields for the selected Classic RM 1351 and Deep RM 1391 cases, plus every encounter decision in day/title/label/order/policy. Choice IDs/indices match unchanged game data (7 Classic decisions, 10 Deep decisions per variant).', '- Both diagnostic runs exit 0. Immutable reference CLI runs exit 1 because their small matrix retains the same acceptance failures; that output is preserved, not treated as a parity failure.', '- The first before diagnostic did not compile because five extra JSON fields exceeded the existing macro recursion limit. Its original patch/freeze/log are preserved in `trace-rm-json-recursion-attempt/`. Splitting the same distance observations into a nested JSON value fixed only the instrumentation. No suppression or test expectation was added.', '', '| Variant | Diagnostic seconds | Immutable diagnostic SHA256 |', '|---|---:|---|']
for phase in ['before','after']:
    m=json.loads((b/('trace-rm-'+phase+'-run.json')).read_text());lines.append(f'| {phase} | {m["commands"]["diagnostic"]["seconds"]:.3f} | `{m["binary_sha256"]}` |')
lines+=['', 'Current identical instrumentation patch SHA256: `d12802f2bceec787c00b30e12932b202938fcb3be55be0e3c5c5f3a4cb5c9f4f`. All 538 input hashes remain unchanged after each successful compile and analysis. Cargo has been released; these hooks are not integrated in the shared tester.', '', '## Exact failed-day accounting','', '| Case | Before moving/total; stationary days | After moving/total; stationary days |', '|---|---|---|']
for case,v in d['cases'].items():
    x=v['before'];y=v['after'];sx=x['summary'];sy=y['summary'];lines.append(f'| {case} | {sx["travel_days"]+sx["partial_travel_days"]}/{sx["days_survived"]}; {x["stationary_days"]} | {sy["travel_days"]+sy["partial_travel_days"]}/{sy["days_survived"]}; {y["stationary_days"]} |')
lines+=['', 'All observed travel-step settings in these four traces are **Heated / Quiet**, despite the initial strategy setting being Steady. The camp decisions below are illness requests, not low-sanity auto-rest: sanity is 8–10, the automatic-rest threshold is 5, and `should_auto_rest` is false. Increasing camp sanity recovery therefore does not address these events.', '', '| Illness day | Baseline: one driving leg before the same camp | Candidate: immediate camp | Illness at camp |', '|---|---|---|---|']
for case,day in [('Classic-1351',14),('Deep-1391',6),('Deep-1391',16)]:
    x=d['cases'][case]['before'];y=d['cases'][case]['after'];cx=next(a for a in x['actions'] if a['action']=='camp_rest' and a['before']['day']==day);cy=next(a for a in y['actions'] if a['action']=='camp_rest' and a['before']['day']==day);drive=[a for a in x['actions'] if a['action']=='travel_step' and a['before']['day']==day and a['driving_minutes']>0][-1];old=cx['before'];new=cy['before']
    lines.append(f'| {case}, day {day} | {drive["before"]["clock"]}–{drive["after"]["clock"]}: {drive["driving_minutes"]} driving minutes / {drive["miles"]:.6f} internal miles; camp at {old["clock"]} | Camp at {new["clock"]}; 0 driving minutes that day | {new["illness_days_remaining"]} illness days remaining; rest_requested=true; sanity {old["stats"]["sanity"]} → {new["stats"]["sanity"]} |')
lines += ['', 'The illness hit is the same calendar day in each paired case. In the baseline, the simulator checks camp, then applies pace/diet (which initializes the day and rolls illness), then travels once. On the next loop it sees the pending illness-rest request. In the candidate, overnight work has already initialized that day before returning; the first camp check sees the same request and acts immediately. The earlier one-hour drive was real and correctly recorded in the baseline, but was allowed by stale decision timing—not erased by the candidate.', '', 'Classic 1351 day 20 is a separate full active-day schedule, with no camp:', '', '| Action | Time | Active minutes | Mileage/driving change |', '|---|---|---:|---|']
after=d['cases']['Classic-1351']['after']
for action in ['crew_care','town_conversation','town_work','encounter']:
    a=next(a for a in after['actions'] if a['action']==action and a['before']['day']==20);lines.append(f'| {action} | {a["before"]["clock"]}–{a["after"]["clock"]} | {a["active_minutes"]} | {a["miles"]} miles / {a["driving_minutes"]} driving minutes |')
lines+=['', 'Those 300 minutes fill 08:00–13:00 exactly. The encounter is `sat_bridge_bullets`, choice 2, “Wish them luck and take the reopened lane.” Travel begins on day 21. The baseline had reached this town on day 19 and moved its crew-care interaction to day 21, so day 20 retained driving time. This is changed arrival/action timing, not a missing ledger row.', '', 'Deep 1391’s final hearing crosses midnight in the candidate’s active-day model:', '', '| Variant | Hearing time | Active minutes | Last-day stationary portion |', '|---|---|---:|---:|']
for phase in ['before','after']:
    a=next(a for a in d['cases']['Deep-1391'][phase]['actions'] if a['action']=='hearing');x=a['before'];y=a['after'];portion=y['clock_minutes']-480 if y['day']>x['day'] else 0;lines.append(f'| {phase} | Day {x["day"]} {x["clock"]} → day {y["day"]} {y["clock"]} | {a["active_minutes"]} | {portion} min |')
lines+=['', 'Both hearings cost exactly 120 active minutes, with no driving. The candidate’s 18 minutes on day 25 are therefore a real stationary day and must remain counted. Classic 1351’s day-24 hearing is stationary in both variants.', '', '## Ledger and clock conservation','', '| Variant/case | Stationary action pairs checked | Maximum recorded-mile conservation error | Lost/decreased earned-day records |', '|---|---:|---:|---:|']
for case,v in d['cases'].items():
    for phase,r in v.items():
        c=r['ledger_conservation'];lines.append(f'| {phase} {case} | {r["stationary_action_conservation"]["action_count"]} | {abs(c["difference"]):.9f} mi | 0 |')
lines += ['', 'Across **150 stationary action pairs**, actual miles, total driving minutes, and fractional driving-fatigue remainder remain exactly unchanged. No cumulative mileage or driving counter decreases. For every observed day, its largest recorded mileage is retained in the final ledger; no same-day mileage reset occurs. Summing the final per-day f32 mileage differs from cumulative mileage only by ≤0.000283 internal miles. The conservation diagnostic uses a 0.001-mile floating-point comparison tolerance; no acceptance threshold or production value changes.', '', '## Production implications','', 'The Activity correction makes the completed-action state truthful even when the retained movement guard becomes harder to satisfy. A ledger patch, an extra pre-rest drive, deferring illness again, or changing the bot would conceal these real costs. Camp +8 would not resolve these illness requests because recovery strength is not their trigger.', '', 'Existing illness controls are `DISEASE_DAILY_CHANCE=0.012`, `DISEASE_COOLDOWN_DAYS=5`, duration 2–4 days, and a 0.85 travel multiplier. Those are genuine model controls if a later isolated recovery-frequency experiment is approved; this diagnosis selects no value. Classic’s day-20 five-hour workload and the final hearing remain real time obligations even if illness frequency changes. These two seeds do not justify a global guarantee about all remaining failed runs.', '', 'Relevant unchanged source owners:', '', '- `dystrail-game/src/activities.rs:75–114` in the Activity candidate: completed timed-activity boundary.', '- `dystrail-game/src/state.rs:3260`: once-only daily initialization; `:3892–3952`: daily illness and explicit rest request.', '- `dystrail-game/src/constants.rs:145–155`: illness frequency, cooldown, duration, and penalties.', '- `dystrail-game/src/camp.rs:57–114`: full rest and illness recovery.', '- `dystrail-tester/src/logic/simulation.rs:138–186` in the uninstrumented base: camp check before lazy daily initialization; `:242–258`: existing camp policy; `:203–204`: hearing’s 120-minute clock; `:260–295`: encounter and crew-care costs.', '- `dystrail-game/src/journal.rs:117`: unchanged low-level active-time accounting.', '', 'All referenced source paths resolve under `/tmp/dystrail-retune-2026-09-13/pace-crossing-health038-source`, except the Activity boundary under its `-activity-source` sibling. Full immutable before/after references, all day snapshots, exact per-action values and machine-checked conservation results are preserved alongside this report.', '']
p=b/'trace-rm-activity-report.md';p.write_text('\n'.join(lines))
# Durable archive: small proof files verbatim; large repetitive traces deterministically compressed.
dst=Path('/Users/vanna/Source/Dystrail/docs/ux/review-2026-09-11/implementation/campaign/retune-2026-09-13');arch={'files':{},'compressed_originals':{},'report_sha256':sha(p),'selected_product_change':False}
selected=[p for p in b.glob('trace-rm*') if p.is_file() and p.suffix in {'.json','.jsonl','.log','.csv','.patch','.md'}]
selected += [b/'run_rm_activity_trace.py',b/'analyze_rm_activity_trace.py',b/'write_rm_activity_report.py']
for src in sorted(selected):
    if src.stat().st_size>100000 or src.suffix=='.csv':
        data=src.read_bytes();buf=io.BytesIO()
        with gzip.GzipFile(filename='',mode='wb',fileobj=buf,mtime=0,compresslevel=9) as f:f.write(data)
        output=buf.getvalue();assert gzip.decompress(output)==data;target=dst/(src.name+'.gz');target.write_bytes(output);arch['compressed_originals'][target.name]={'original_name':src.name,'original_sha256':sha(src),'original_bytes':len(data),'mtime':0,'filename':'','roundtrip_exact':True}
    else:
        target=dst/src.name;shutil.copy2(src,target)
    arch['files'][target.name]=sha(target)
failed=b/'trace-rm-json-recursion-attempt';destfailed=dst/failed.name;shutil.copytree(failed,destfailed,dirs_exist_ok=True)
for q in sorted(destfailed.iterdir()):arch['files'][str(q.relative_to(dst))]=sha(q)
for phase in ['before','after']:
    freeze=json.loads((b/('trace-rm-'+phase+'-freeze.json')).read_text());source=Path(freeze['source']);assert all(sha(source/name)==h for name,h in freeze['inputs'].items())
arch['frozen_source_inputs_unchanged']=True;archive=dst/'trace-rm-activity-archive.json';archive.write_text(json.dumps(arch,indent=2)+'\n');print(json.dumps({'report':str(dst/p.name),'report_sha256':sha(p),'archive':str(archive),'archive_sha256':sha(archive),'files':len(arch['files']),'large_traces_compressed':len(arch['compressed_originals'])},indent=2))
