"""Accept C08 source/runtime review, retaining the full unfinished feature scope."""
import csv,hashlib,json
from collections import Counter
from pathlib import Path
root=Path(__file__).resolve().parents[2];r=root/'review/art-satire';manifest=json.loads(Path('/private/tmp/dystrail-art-satire-build/offline-manifest.json').read_text());assert manifest['revision']=='b3ef721614ca78d87e24'
for log,required in [('road-c08-tests.log','8 passed'),('road-c08-final-tests.log','6 passed'),('road-c08-native.log','100 passed; 0 failed')]:assert required in (r/log).read_text()
assert all(a['opaque'] for a in json.loads((r/'road-c08-opacity.json').read_text()))
assets=json.loads((r/'road-c08-source-assets.json').read_text());c=json.loads((r/'asset-catalog.json').read_text());audit=json.loads((r/'religious-symbol-audit/source-review.json').read_text())
for v,s in assets.items():
 raw=(root/s['packaged']).read_bytes();assert raw==Path(s['source']).read_bytes();digest=hashlib.sha256(raw).hexdigest();assert digest==s['sha256'];id=f'road-c08-{v.lower()}-20260914'
 entry={'id':id,'path':s['packaged'],'source_image':s['source'],'sha256':digest,'method':'built-in image generation','background':'opaque','status':'integrated_render_reviewed','source_revision':'source-refresh-20260914','prompt':'review/art-satire/road-c08-generation-prompts.json','correction_prompts':'review/art-satire/road-c08-correction-prompts.json','row_boundaries':[0,512,1024],'column_boundaries':[0,768,1536],'source_inset':8,'runtime_cells':[0,1,2,3],'religious_symbol_review':'All four source frames and representative desktop/mobile runtime compositions inspected; no religious imagery observed.'}
 c['assets']=[a for a in c['assets'] if a['id']!=id]+[entry];name=f'scenes-v2/{id}.png';audit=[a for a in audit if a['asset']!=name]+[{'asset':name,'sha256':digest,'source_review':'Map club, café access display and carpool picnic: feminine or neutral locals, unmarked props, plain paper toy crown without emblems. No religious identifiers observed.','render_review':'road-c08-results, road-c08-final-results, road-c08-client, road-c08-final-client. Source/readout labels, selected outcomes, lighting, weather and caption reviewed.'}]
for u in c['units']:
 if u['id'].startswith('ENC-C08-'):
  u['production_status']='integrated_render_reviewed';u['asset']={'atlas':f"road-c08-{u['variant'].lower()}-20260914",'offer_cell':0,'choice_cells':[1,2,3]};u['art_constraint']='Diverse feminine/neutral fictional locals; no religious identifiers or flags. Offer precedes donation or meal. Matching maps preserve geography. Café chair remains empty/outside, moves with donation, unlocks only with evidence choice; weather is clipped to exterior. Toll invoice is paper, not cash; plain toy crown is put away only after checking maps. Native localized offer labels and readable transcript; bottom-left title without crew bust.'
assert len(c['units'])==644
(r/'asset-catalog.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');(r/'religious-symbol-audit/source-review.json').write_text(json.dumps(audit,indent=2)+'\n')
p=root/'docs/ux/enhancement-review-2026-09-13/features/art-and-satire/satire-art-coverage.csv'
with p.open(newline='') as f:rd=csv.DictReader(f);fields=rd.fieldnames;rows=list(rd)
lookup={u['id']:u for u in c['units']};assert len(rows)==644 and set(lookup)=={a['unit_id'] for a in rows}
for row in rows:row['asset_mapping_status']=lookup[row['unit_id']]['production_status']
with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
counts=dict(Counter(u['production_status'] for u in c['units']))
record={'status':'integrated_render_reviewed','build':manifest['revision'],'units':['ENC-C08-'+v for v in 'ABC'],'runtime':'classic_mutual_aid_dispatch','gameplay_frames':12,'locales':['en','es','it','ar'],'other_locales':'Explicit English narrative fallback; unrelated locale/source values preserved.','source_refresh':'road-c08-source-refresh.json','source_qualification':'road-c08-fact-review.json; AP live re-fetch failed, so its previously verified workshop source was retained without new factual claims.','verification':{'native_tests':100,'native_clippy':'passed','wasm_clippy':'passed, including final window-layer change','choice_language_variant_actions_per_platform':36,'desktop_mobile_scene_cases':8,'final_weather_and_hearing_cases':6,'offline_assets':173,'bytes':manifest['bytes'],'hearing_engine_files_preserved':7,'hearing_locale_subtrees_preserved':20,'main_source_snapshot_files_preserved':60,'supplied_game_client':'Evidence choice on C and shared meal in B; actual effects and rendered state inspected.'},'render_review':['All three source atlases inspected. Café realism/backdrop and invoice-as-cash errors corrected before acceptance. All assets fully opaque.','Desktop/mobile offered and selected cells, translated labels, enlarged Arabic, keyboard choices and zero-supplies options checked.','Morning/day/dusk/night and weather inspected. Café exterior precipitation is masked from indoor host/table; lettered signs have visible localized transcripts.','All A/B/C choices preserve simulation effects/RNG. Reload, offline, legacy outcome, duplicate action and day boundary checks passed.','C supplied client: sanity 5 to 6, supplies unchanged, 2 receipts including existing persona bonus. B final client: supplies 8 to 7, morale 5 to 7, same five surviving travelers.','Hearing failed vote, secured win, exhaustion and narrow-layout regressions passed.'],'catalog_counts':counts,'source_audit_images':len(audit),'remaining':['Most scene families and derived cast coverage unfinished.','36 proposed encounter-mechanics records stay explicit inactive dependencies.','Whole-game route, accessibility, release/update and performance acceptance pending; candidate about 214 MB.']}
(r/'road-c08-review.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n')
p=r/'road-c08-corrections.json';d=json.loads(p.read_text());d['status']='Corrected sources and final desktop/mobile runtime compositions inspected; integrated and verified.';p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps({'counts':counts,'source_audit_images':len(audit)}))
