import json
from pathlib import Path
# Rows: name, description, fact, overlay, two overlay lines, then three label/outcome pairs.
rows={
'es':[
['Cartografía patriótica','El cambio de nombre del golfo por Trump ha dejado a un club de mapas de carretera con cartas antiguas y nuevas etiquetas federales. Piden a tu grupo que ayude a preparar una comparación pública. La voluntaria ha revisado la costa con cuidado. No ha hecho el menor esfuerzo por moverse.','La orden del 20 de enero de 2025 dispuso el uso federal de Golfo de América. Cambió el nombre federal, no la costa ni el uso internacional universal. El club y el diálogo son ficticios.','MISMA COSTA. NUEVO NOMBRE FEDERAL.','MISMA COSTA.','NUEVO NOMBRE FEDERAL.','Donar provisiones para comparar mapas','Donas provisiones y ayudas a documentar los nombres. La voluntaria confirma con una regla que la grandeza no añadió costa.','Compartir comida con el club','Compartes comida y todos inventan nombres patrióticos para las migas. El plato se convierte en el primer territorio disputado que desaparece.','Comparar y guardar los mapas','Comparas y guardas los mapas, con alivio al ver que las coordenadas no cambiaron. La voluntaria permite que la brújula siga siendo neutral.'],
['Un lugar en la mesa','Inspirados por la cena de Trump para grandes inversores de su criptomoneda meme, vecinos de una cafetería preparan una exposición sobre el acceso al gobierno. Piden ayuda a tu grupo. El puesto de una votante común incluye una silla plegable al otro lado de la ventana.','Trump recibió a grandes inversores de su criptomoneda meme en su club de golf de Virginia el 22 de mayo de 2025; hubo unas 220 invitaciones. La inversión daba acceso; esto no demuestra que se comprara una decisión política. La cafetería y sus vecinos son ficticios.','VOTANTE COMÚN','VOTANTE','COMÚN','Donar provisiones para la exposición','Donas provisiones y ayudas a documentar la exposición. La voluntaria acerca la silla de la votante. Ahora puede oler el acceso.','Compartir comida y participar en el ensayo','Compartes comida y ensayáis la cena de la votante. Todos se ríen cuando la camarera presenta el menú mirando por unos prismáticos.','Revisar y guardar la noticia de la cena','Revisas y guardas la noticia sobre la cena de inversores. La dueña abre el candado de la silla exterior. «Aquí no exigimos una inversión mínima».'],
['Exención real del peaje','Trump intentó terminar con el peaje por congestión de Nueva York y publicó «Viva el rey». Un juez bloqueó el intento. En un pícnic de viajeros, una mensajera neoyorquina muestra su factura. Las anfitrionas aceptan provisiones para registrar testimonios, o comida para compartir. La factura acepta dinero, no proclamas reales.','En febrero de 2025 el gobierno intentó retirar la autorización del peaje neoyorquino y Trump publicó «LONG LIVE THE KING!». El 3 de marzo de 2026 un tribunal federal de distrito rechazó esa retirada por los motivos alegados. Es un fallo fechado, no una descripción de todas las apelaciones posteriores ni del fin permanente del peaje. La mensajera y el pícnic son ficticios.','VIVA EL REY','VIVA','EL REY','Donar provisiones para registrar testimonios','Donas provisiones y conservas los testimonios. La mensajera adjunta la publicación presidencial a su factura del peaje. No se ponen de acuerdo sobre quién gobierna el reino.','Compartir comida y escuchar a la mensajera','Compartes comida y escuchas su historia. «Probé a decirle Viva el rey a la factura», dice. «Resulta que quería Viva mi tarjeta de débito».','Comparar y guardar los mapas del peaje','Guardas los mapas antiguos y actuales y entiendes el fallo. La mensajera guarda su corona de juguete. El límite de Manhattan no se deja mover por un sombrero.']
],
'it':[
['Cartografia patriottica','La rinomina del Golfo voluta da Trump ha lasciato un club stradale di cartografia con vecchie mappe e nuove etichette federali. Chiedono al gruppo di aiutare a preparare un confronto pubblico. La volontaria ha controllato bene la costa. Non ha fatto il minimo sforzo per spostarsi.','L’ordine del 20 gennaio 2025 dispose l’uso federale del nome Golfo d’America. Cambiò il nome federale, non la costa né ogni uso internazionale. Il club e il dialogo sono inventati.','STESSA COSTA. NUOVO NOME FEDERALE.','STESSA COSTA.','NUOVO NOME FEDERALE.','Donare provviste per confrontare le mappe','Doni provviste e aiuti a documentare le etichette. La volontaria verifica con un righello che la grandezza non ha aggiunto costa.','Condividere cibo con il club','Condividi cibo e tutti inventano nomi patriottici per le briciole. Il piatto diventa il primo territorio conteso a sparire.','Confrontare e salvare le mappe','Confronti e salvi le mappe: che sollievo, le coordinate sono immutate. La volontaria autorizza la bussola a restare neutrale.'],
['Un posto a tavola','Ispirati dalla cena di Trump per i maggiori investitori della sua meme coin, gli abitanti preparano in un caffè una mostra sull’accesso al governo. Chiedono aiuto al gruppo. Il posto per una normale elettrice comprende una sedia pieghevole fuori dalla finestra.','Trump ospitò importanti investitori della sua meme coin nel suo golf club in Virginia il 22 maggio 2025; gli inviti furono circa 220. L’investimento era legato all’accesso; non dimostra l’acquisto di una decisione politica. Il caffè e gli abitanti sono inventati.','ELETTRICE COMUNE','ELETTRICE','COMUNE','Donare provviste per la mostra','Doni provviste e aiuti a documentare la mostra. La volontaria avvicina la sedia dell’elettrice. Ora può annusare l’accesso.','Condividere cibo e partecipare alla prova','Condividi cibo e provate la cena dell’elettrice. Tutti ridono quando la cameriera presenta il menu guardando nel binocolo.','Verificare e salvare la notizia della cena','Verifichi e salvi la notizia sulla cena degli investitori. La proprietaria apre il lucchetto della sedia esterna. «Qui nessun investimento minimo».'],
['Esenzione reale dal pedaggio','Trump tentò di abolire il pedaggio anti-congestione di New York e pubblicò «Viva il re». Un giudice bloccò il tentativo. A un picnic tra pendolari, una corriera di New York mostra il conto. Le ospiti chiedono provviste per registrare le testimonianze o cibo da condividere. Il conto accetta denaro, non proclami reali.','Nel febbraio 2025 il governo tentò di revocare l’autorizzazione al pedaggio di New York e Trump pubblicò «LONG LIVE THE KING!». Il 3 marzo 2026 un tribunale federale distrettuale respinse la revoca sui motivi addotti. Si tratta di quella sentenza, non di tutti gli appelli successivi né della fine permanente del pedaggio. La corriera e il picnic sono inventati.','VIVA IL RE','VIVA','IL RE','Donare provviste per registrare i racconti','Doni provviste e conservi le testimonianze. La corriera allega il post presidenziale al conto del pedaggio. Non concordano su chi governi il regno.','Condividere cibo e ascoltare la corriera','Condividi cibo e ascolti il suo racconto. «Ho provato a dire Viva il re al conto», racconta. «Voleva Viva la mia carta di debito».','Confrontare e salvare le mappe dei pedaggi','Salvi le mappe vecchie e attuali e chiarisci la sentenza. La corriera ripone la corona giocattolo. Il confine di Manhattan non si sposta per un copricapo.']
],
'ar':[
['خرائط وطنية','ترك تغيير ترامب لاسم الخليج نادي خرائط على الطريق أمام خرائط قديمة وتسميات اتحادية جديدة. يطلبون من طاقمكم المساعدة في إعداد مقارنة للعرض. فحصت المتطوعة الساحل بعناية. لم يبذل أي جهد للتحرك.','وجّه أمر 20 يناير 2025 إلى استخدام اسم خليج أمريكا اتحاديًا. غيّر التسمية الاتحادية، لا الساحل ولا جميع الاستخدامات الدولية. النادي والحوار خياليان.','الساحل نفسه. اسم اتحادي جديد.','الساحل نفسه.','اسم اتحادي جديد.','التبرع بمؤن لمقارنة الخرائط','تتبرعون بمؤن وتساعدون في توثيق التسميات. تؤكد المتطوعة بالمسطرة أن العظمة لم تضف أي ساحل.','مشاركة الطعام مع النادي','تشاركون الطعام ويبتكر الجميع أسماء وطنية للفتات. يصبح الطبق أول أرض متنازع عليها تختفي.','مقارنة الخرائط وحفظها','تقارنون الخرائط وتحفظونها، وترتاحون لأن الإحداثيات لم تتغير. تمنح المتطوعة البوصلة إذنًا بالبقاء محايدة.'],
['مكان على المائدة','استلهم سكان قرب مقهى على الطريق عشاء ترامب لكبار مستثمري عملته الميمية، ويعدّون عرضًا عن الوصول إلى الحكومة. يطلبون مساعدة طاقمكم. يشمل مكان الناخبة العادية كرسيًا قابلًا للطي خارج النافذة.','استضاف ترامب كبار مستثمري عملته الميمية في ناديه للغولف بفرجينيا يوم 22 مايو 2025، ووُجّهت نحو 220 دعوة. ارتبط الاستثمار بإتاحة الوصول؛ ولا يثبت ذلك شراء قرار سياسي. المقهى والسكان خياليون.','ناخبة عادية','ناخبة','عادية','التبرع بمؤن للعرض','تتبرعون بمؤن وتساعدون في توثيق العرض. تقرّب المتطوعة كرسي الناخبة. صار بإمكانه شم رائحة الوصول.','مشاركة الطعام والانضمام إلى البروفة','تشاركون الطعام وتتدربون على عشاء الناخبة. يضحك الجميع حين تقدم النادلة قائمة الطعام وهي تنظر بمنظار.','التحقق من تقرير العشاء وحفظه','تتحققون من تقرير عشاء المستثمرين وتحفظونه. تفتح صاحبة المقهى قفل الكرسي الخارجي. «لا حد أدنى للاستثمار هنا».'],
['إعفاء ملكي من الرسم','حاول ترامب إنهاء رسم الازدحام في نيويورك ونشر «عاش الملك». أوقف قاضٍ المحاولة. في نزهة لمستخدمي السيارات المشتركة، تعرض ساعية من نيويورك فاتورتها. تطلب المضيفات مؤنًا لتسجيل روايات السائقين أو طعامًا للمشاركة. تقبل الفاتورة المال، لا الإعلانات الملكية.','في فبراير 2025 حاولت الإدارة سحب الموافقة على رسم الازدحام في نيويورك ونشر ترامب «LONG LIVE THE KING!». وفي 3 مارس 2026 رفضت محكمة اتحادية ابتدائية الإنهاء استنادًا إلى الأسباب المطروحة. هذا وصف لذلك الحكم المؤرخ، لا لجميع الطعون اللاحقة ولا لنهاية دائمة للرسم. الساعية والنزهة خياليتان.','عاش الملك','عاش','الملك','التبرع بمؤن لتسجيل روايات السائقين','تتبرعون بمؤن وتحفظون الروايات. ترفق الساعية المنشور الرئاسي بفاتورة الرسم. يختلفان حول من يدير المملكة.','مشاركة الطعام وسماع قصة الساعية','تشاركون الطعام وتسمعون قصتها. تقول: «جرّبت قول عاش الملك للفاتورة. اتضح أنها تريد عاشت بطاقة الخصم الخاصة بي».','مقارنة خرائط الرسوم وحفظها','تحفظون الخرائط القديمة والحالية وتفهمون الحكم. تضع الساعية تاجها اللعبة في الحقيبة. لا تحرك أغطية الرأس حدود مانهاتن.']
]}
keys=['name','desc','fact','overlay_0','overlay_line1','overlay_line2','choice_0','log_0','choice_1','log_1','choice_2','log_2'];d={lang:{'ENC-C08-'+v:dict(zip(keys,row,strict=True)) for v,row in zip('ABC',values,strict=True)} for lang,values in rows.items()};Path(__file__).with_name('road-c08-translations.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
