"""Authored local conversations. Facts were checked September 11, 2026; remarks are fiction.

Each tuple: town, source, evidence status, fact (en/es/it/ar), resident (en/es/it/ar).
Historical dates and attribution distinguish completed actions from proposals and estimates.
"""
FACTS = [
('Seattle', 'https://magazine.washington.edu/feature/federal-funding-cuts-to-the-uw-will-shut-down-life-saving-research-facilities/', 'documented',
 ('UW researchers reported in June 2025 that the Trump administration had frozen or terminated active research grants, including work on cancer and infectious diseases.',
  'Investigadores de la UW informaron en junio de 2025 de que la administración Trump había congelado o cancelado subvenciones activas, incluidas investigaciones sobre cáncer y enfermedades infecciosas.',
  'Nel giugno 2025 ricercatori della UW riferirono che l’amministrazione Trump aveva congelato o revocato finanziamenti attivi, anche per studi su cancro e malattie infettive.',
  'أفاد باحثو جامعة واشنطن في يونيو 2025 بأن إدارة ترامب جمّدت أو ألغت منحاً بحثية قائمة، منها أبحاث السرطان والأمراض المعدية.'),
 ('The lab is applying for a new grant to determine whether cancer can be defeated by changing its name to DEI.',
  'El laboratorio solicita otra subvención para comprobar si al cáncer se le puede vencer cambiándole el nombre a DEI.',
  'Il laboratorio chiede un nuovo finanziamento per capire se il cancro si sconfigga ribattezzandolo DEI.',
  'المختبر يطلب منحة جديدة ليعرف إن كان تغيير اسم السرطان إلى «التنوع والإنصاف والشمول» كافياً للقضاء عليه.')),
('Portland', 'https://www.portland.gov/federal/federal-troops', 'documented',
 ('Trump announced a Portland troop deployment in September 2025. The city reports that court orders blocked it and the Guard was never lawfully deployed there.',
  'Trump anunció un despliegue militar en Portland en septiembre de 2025. La ciudad informa de que los tribunales lo bloquearon y la Guardia nunca se desplegó legalmente allí.',
  'Trump annunciò l’invio di truppe a Portland nel settembre 2025. Secondo la città, i tribunali lo bloccarono e la Guardia non vi fu mai dispiegata legalmente.',
  'أعلن ترامب إرسال قوات إلى بورتلاند في سبتمبر 2025. وتقول المدينة إن أوامر قضائية منعته وإن الحرس لم يُنشر فيها بصورة قانونية.'),
 ('Our invasion was canceled. The coffee shops have agreed to remain a national emergency until the next news cycle.',
  'Cancelaron nuestra invasión. Las cafeterías aceptaron seguir siendo una emergencia nacional hasta el próximo ciclo de noticias.',
  'Hanno annullato la nostra invasione. I bar resteranno un’emergenza nazionale fino al prossimo ciclo di notizie.',
  'أُلغي غزونا. ووافقت المقاهي على البقاء حالة طوارئ وطنية حتى دورة الأخبار المقبلة.')),
('San Francisco', 'https://www.sfcityattorney.org/2025/02/07/san-francisco-leads-lawsuit-protecting-sanctuary-jurisdictions-from-illegal-federal-overreach/', 'documented',
 ('San Francisco led a February 2025 lawsuit challenging Trump administration threats to withhold federal funding from jurisdictions with sanctuary policies.',
  'San Francisco encabezó en febrero de 2025 una demanda contra las amenazas de Trump de retirar fondos federales a las jurisdicciones con políticas santuario.',
  'Nel febbraio 2025 San Francisco guidò una causa contro le minacce dell’amministrazione Trump di togliere fondi federali alle giurisdizioni con politiche di protezione degli immigrati.',
  'قادت سان فرانسيسكو في فبراير 2025 دعوى ضد تهديدات إدارة ترامب بحجب التمويل الفيدرالي عن المناطق التي تتبنى سياسات الملاذ.'),
 ('We budgeted for buses. Apparently the new federal matching requirement is one lawsuit per bus.',
  'Presupuestamos autobuses. Al parecer, la nueva aportación federal exige una demanda por autobús.',
  'Avevamo stanziato fondi per gli autobus. Pare che il nuovo cofinanziamento federale richieda una causa per autobus.',
  'خصصنا ميزانية للحافلات. يبدو أن شرط المساهمة الفيدرالية الجديد هو دعوى قضائية لكل حافلة.')),
('Los Angeles', 'https://www.gov.ca.gov/wp-content/uploads/2025/06/FILE_6924.pdf', 'documented',
 ('On June 7, 2025, Trump authorized federalizing at least 2,000 National Guard personnel. California challenged their deployment to Los Angeles in court.',
  'El 7 de junio de 2025 Trump autorizó federalizar al menos 2.000 miembros de la Guardia Nacional. California impugnó judicialmente su despliegue en Los Ángeles.',
  'Il 7 giugno 2025 Trump autorizzò il passaggio di almeno 2.000 membri della Guardia Nazionale al comando federale. La California contestò in tribunale il dispiegamento a Los Angeles.',
  'في 7 يونيو 2025 أجاز ترامب وضع ما لا يقل عن 2000 من الحرس الوطني تحت القيادة الفيدرالية. وطعنت كاليفورنيا قضائياً في نشرهم بلوس أنجلوس.'),
 ('Hollywood normally pays extras. This production billed the audience and forgot to ask the location owner.',
  'Hollywood suele pagar a los extras. Esta producción cobró al público y olvidó pedir permiso para el rodaje.',
  'Hollywood di solito paga le comparse. Questa produzione ha fatturato al pubblico e dimenticato il permesso per girare.',
  'هوليوود عادة تدفع للكومبارس. هذا الإنتاج أرسل الفاتورة للجمهور ونسي استئذان صاحب الموقع.')),
('Sacramento', 'https://hsr.ca.gov/wp-content/uploads/2026/02/2026-HSR-Draft-Business-Plan-02282026.pdf', 'documented',
 ('California’s 2026 high-speed rail plan records $4.1 billion in federal awards rescinded by the Trump–Vance administration. State funding kept the project moving.',
  'El plan ferroviario de California de 2026 registra 4.100 millones de dólares en ayudas federales revocadas por Trump y Vance. La financiación estatal mantuvo el proyecto.',
  'Il piano ferroviario californiano del 2026 registra 4,1 miliardi di dollari di fondi federali revocati da Trump e Vance. Il finanziamento statale ha mantenuto attivo il progetto.',
  'تسجل خطة قطار كاليفورنيا السريع لعام 2026 إلغاء إدارة ترامب وفانس منحاً فيدرالية بقيمة 4.1 مليارات دولار. وأبقى تمويل الولاية المشروع مستمراً.'),
 ('The train is still under construction. The federal funding reached its destination much faster: the shredder.',
  'El tren sigue en obras. Los fondos federales llegaron mucho antes a su destino: la trituradora.',
  'Il treno è ancora in costruzione. I fondi federali sono arrivati molto prima a destinazione: il tritadocumenti.',
  'القطار ما زال قيد الإنشاء. التمويل الفيدرالي بلغ وجهته أسرع بكثير: آلة إتلاف الورق.')),
('San Diego', 'https://www.sandiego.gov/sites/default/files/2025-10/fy2025-citywide-annual-grants-evaluation-final.pdf', 'documented',
 ('San Diego’s FY2025 grants report describes a translation guide for changing grant-application language in response to Trump administration policy changes.',
  'El informe de subvenciones de San Diego de 2025 describe una guía para cambiar el lenguaje de las solicitudes ante las nuevas políticas de Trump.',
  'Il rapporto sulle sovvenzioni di San Diego del 2025 descrive una guida per modificare il linguaggio delle domande in risposta alle politiche di Trump.',
  'يصف تقرير منح سان دييغو للسنة المالية 2025 دليلاً لتعديل لغة طلبات المنح استجابة لتغييرات سياسات إدارة ترامب.'),
 ('The same sewer project is now patriotic liquid freedom. The wastewater has declined to comment on its pronouns.',
  'La misma obra de alcantarillado ahora es libertad líquida patriótica. Las aguas residuales no han querido comentar sus pronombres.',
  'La stessa fognatura ora è libertà liquida patriottica. Le acque reflue non commentano i propri pronomi.',
  'مشروع الصرف نفسه أصبح «حرية سائلة وطنية». ومياه الصرف امتنعت عن التعليق على ضمائرها.')),
('Spokane', 'https://my.spokanecity.org/news/releases/2025/09/23/proposed-resolution-outlines-city-of-spokanes-federal-priorities/', 'documented',
 ('Spokane’s September 2025 federal priorities called for restoring a $19.9 million Community Change Grant awarded to the city and Gonzaga, then rescinded by the Trump administration.',
  'Spokane pidió en septiembre de 2025 recuperar una subvención comunitaria de 19,9 millones de dólares concedida a la ciudad y a Gonzaga, y revocada por Trump.',
  'Nel settembre 2025 Spokane chiese di ripristinare un finanziamento comunitario di 19,9 milioni di dollari assegnato alla città e a Gonzaga, poi revocato dall’amministrazione Trump.',
  'طالبت سبوكان في سبتمبر 2025 بإعادة منحة التغيير المجتمعي البالغة 19.9 مليون دولار، التي مُنحت للمدينة وغونزاغا ثم ألغتها إدارة ترامب.'),
 ('Community Change was apparently too literal. They changed the community’s grant balance to zero.',
  'Cambio Comunitario resultó demasiado literal: cambiaron el saldo de la subvención a cero.',
  'Cambiamento comunitario era fin troppo letterale: hanno cambiato il saldo del finanziamento in zero.',
  'أخذوا «التغيير المجتمعي» بحرفيته: غيّروا رصيد منحة المجتمع إلى صفر.')),
('Missoula', 'https://www.umt.edu/sponsored-programs/exec-orders/funding-freeze.php', 'documented',
 ('The University of Montana told researchers on January 29, 2025 that the blanket federal funding-freeze memo was rescinded, while other executive-order reviews and agency pauses remained.',
  'La Universidad de Montana comunicó el 29 de enero de 2025 que se había retirado la congelación general, pero seguían otras revisiones por decretos y pausas de agencias.',
  'Il 29 gennaio 2025 l’Università del Montana comunicò la revoca del blocco generale dei fondi, mentre restavano altre revisioni per decreti e pause delle agenzie.',
  'أبلغت جامعة مونتانا الباحثين في 29 يناير 2025 بإلغاء مذكرة التجميد الشامل، مع استمرار مراجعات أوامر تنفيذية أخرى وتوقفات لدى الوكالات.'),
 ('The freeze thawed, except for the frozen parts. Our political science department has reclassified this as a weather event.',
  'La congelación se descongeló, salvo las partes congeladas. Ciencias Políticas la ha reclasificado como fenómeno meteorológico.',
  'Il blocco si è scongelato, tranne le parti congelate. Scienze politiche lo ha riclassificato come fenomeno meteorologico.',
  'ذاب التجميد، باستثناء الأجزاء المتجمدة. قسم العلوم السياسية أعاد تصنيفه ظاهرة جوية.')),
('Billings', 'https://dphhs.mt.gov/News/2026/May/USDA-Approves-Gov-Junk-Food-Ban-SNAP', 'documented',
 ('In May 2026, Trump’s USDA approved Montana’s waiver to restrict soda, candy and certain other foods under SNAP, affecting the rules for shoppers across the state.',
  'En mayo de 2026, el USDA de Trump aprobó restricciones de Montana sobre refrescos, dulces y otros alimentos de SNAP, cambiando las reglas para compradores de todo el estado.',
  'Nel maggio 2026 l’USDA di Trump approvò restrizioni del Montana su bibite, dolci e altri alimenti acquistabili con SNAP, modificando le regole per i beneficiari nello stato.',
  'في مايو 2026 وافقت وزارة الزراعة في عهد ترامب على قيود مونتانا على المشروبات الغازية والحلوى وأطعمة أخرى ضمن SNAP، بما يغيّر قواعد التسوق في الولاية.'),
 ('Small government has reached the checkout. Please ask the federal cashier whether your granola bar is a moral failure.',
  'El gobierno mínimo llegó a la caja. Pregunte al cajero federal si su barrita de cereales es un fracaso moral.',
  'Il governo minimo è arrivato alla cassa. Chiedete al cassiere federale se la vostra barretta è un fallimento morale.',
  'وصلت الحكومة الصغيرة إلى صندوق الدفع. اسأل المحاسب الفيدرالي إن كانت حبة الحبوب المغلفة فشلاً أخلاقياً.')),
('Rapid City', 'https://www.nps.gov/badl/planyourvisit/fees.htm', 'documented',
 ('Nearby Badlands National Park lists June 14 as a 2026 fee-free day for eligible visitors, explicitly labeled Flag Day and President Trump’s birthday.',
  'El cercano Parque Nacional Badlands incluye el 14 de junio como día gratuito de 2026 para visitantes elegibles: Día de la Bandera y cumpleaños de Trump.',
  'Il vicino parco nazionale delle Badlands indica il 14 giugno tra le giornate gratuite del 2026 per i visitatori aventi diritto: Festa della bandiera e compleanno di Trump.',
  'تدرج حديقة بادلاندز القريبة يوم 14 يونيو ضمن أيام الإعفاء من الرسوم لعام 2026 للزوار المؤهلين، بعنوان يوم العلم وعيد ميلاد الرئيس ترامب.'),
 ('Millions of years of erosion, finally organized around one man’s birthday. The rocks are awaiting instructions on the cake.',
  'Millones de años de erosión, por fin organizados en torno al cumpleaños de un hombre. Las rocas esperan instrucciones sobre la tarta.',
  'Milioni di anni di erosione, finalmente organizzati attorno al compleanno di un uomo. Le rocce aspettano istruzioni sulla torta.',
  'ملايين السنين من التعرية نُظمت أخيراً حول عيد ميلاد رجل واحد. الصخور تنتظر تعليمات الكعكة.')),
('Sioux Falls', 'https://www.kotatv.com/2025/07/31/feeding-south-dakota-asks-south-dakota-lawmakers-3m-due-federal-cuts/', 'reported',
 ('Feeding South Dakota asked state lawmakers for $3 million in July 2025 after federal USDA cuts reduced its expected food supply by 1.5 million pounds annually.',
  'Feeding South Dakota pidió tres millones de dólares a legisladores estatales en julio de 2025 tras perder 1,5 millones de libras anuales de alimentos por recortes federales del USDA.',
  'Nel luglio 2025 Feeding South Dakota chiese tre milioni di dollari allo stato dopo che i tagli federali USDA avevano ridotto di 1,5 milioni di libbre le forniture alimentari annue previste.',
  'طلبت Feeding South Dakota ثلاثة ملايين دولار من مشرعي الولاية في يوليو 2025 بعدما خفضت اقتطاعات وزارة الزراعة الفيدرالية الغذاء المتوقع بمقدار 1.5 مليون رطل سنوياً.'),
 ('Trump’s efficiency drive found the waste: food that was about to be eaten. We are appealing on behalf of lunch.',
  'La eficiencia de Trump encontró el despilfarro: comida a punto de comerse. Apelamos en nombre del almuerzo.',
  'L’efficienza di Trump ha trovato lo spreco: cibo che stava per essere mangiato. Facciamo ricorso a nome del pranzo.',
  'حملة كفاءة ترامب وجدت الهدر: طعام كان سيُؤكل. نحن نستأنف الحكم نيابة عن الغداء.')),
('Boise', 'https://www.boisestate.edu/research-osp/2025/01/30/federal-funding-update-january-30-2025/', 'documented',
 ('After the Trump funding-freeze memo was withdrawn in January 2025, Boise State still had to identify research awards at risk under the administration’s other executive orders.',
  'Tras retirarse la congelación de Trump en enero de 2025, Boise State aún debía identificar subvenciones de investigación amenazadas por los demás decretos de la administración.',
  'Revocato il blocco dei fondi di Trump nel gennaio 2025, Boise State doveva ancora individuare i finanziamenti alla ricerca a rischio per gli altri decreti dell’amministrazione.',
  'بعد سحب مذكرة تجميد تمويل ترامب في يناير 2025، ظلت جامعة بويزي مطالبة بتحديد المنح البحثية المهددة بأوامر الإدارة التنفيذية الأخرى.'),
 ('My experiment now has two control groups: the one in the lab and the one refreshing the White House website.',
  'Mi experimento tiene dos grupos de control: uno en el laboratorio y otro actualizando la web de la Casa Blanca.',
  'Il mio esperimento ha due gruppi di controllo: quello in laboratorio e quello che aggiorna il sito della Casa Bianca.',
  'صار لتجربتي مجموعتا ضبط: واحدة في المختبر وأخرى تحدّث موقع البيت الأبيض باستمرار.')),
('Salt Lake City', 'https://www.research.utah.edu/features/u-research-leaders-keep-doing-the-science/', 'estimated',
 ('University of Utah leaders estimated in February 2025 that Trump’s proposed NIH overhead cap would cut roughly $45 million from annual research revenue; the policy faced court challenges.',
  'La Universidad de Utah estimó en febrero de 2025 que el tope de gastos indirectos del NIH propuesto por Trump restaría unos 45 millones de dólares anuales; hubo impugnaciones judiciales.',
  'Nel febbraio 2025 l’Università dello Utah stimò che il tetto ai costi indiretti NIH proposto da Trump avrebbe tolto circa 45 milioni di dollari annui; la misura fu contestata in tribunale.',
  'قدّرت جامعة يوتا في فبراير 2025 أن سقف النفقات غير المباشرة المقترح من NIH في عهد ترامب سيخفض إيرادات البحث بنحو 45 مليون دولار سنوياً؛ وواجهت السياسة طعوناً قضائية.'),
 ('The proposal funds the experiment but not the building. Please conduct your breakthrough somewhere with naturally occurring electrical outlets.',
  'La propuesta paga el experimento, pero no el edificio. Haga su descubrimiento donde los enchufes crezcan naturalmente.',
  'La proposta finanzia l’esperimento ma non l’edificio. Fate la vostra scoperta dove le prese elettriche crescono spontanee.',
  'المقترح يمول التجربة دون المبنى. يُرجى تحقيق اكتشافكم في مكان تنمو فيه مقابس الكهرباء طبيعياً.')),
('Reno', 'https://www.unr.edu/nevada-today/news/president-messages/2025-02-11-update-nih-funding', 'estimated',
 ('UNR estimated in February 2025 that the Trump-era NIH overhead proposal threatened over $4 million annually. Its president also noted a judge had temporarily blocked the change.',
  'La UNR estimó en febrero de 2025 que la propuesta de gastos indirectos del NIH amenazaba más de cuatro millones de dólares anuales. Su presidente señaló un bloqueo judicial temporal.',
  'Nel febbraio 2025 la UNR stimò oltre quattro milioni di dollari annui a rischio per la proposta NIH dell’era Trump. Il rettore segnalò anche un blocco giudiziario temporaneo.',
  'قدّرت جامعة نيفادا برينو في فبراير 2025 أن مقترح NIH في عهد ترامب هدد أكثر من أربعة ملايين دولار سنوياً. وأشار رئيسها أيضاً إلى وقف قضائي مؤقت للتغيير.'),
 ('The lab’s new funding model is roulette. At least the casino publishes the odds before taking your equipment money.',
  'El nuevo modelo de financiación del laboratorio es la ruleta. Al menos el casino publica las probabilidades antes de llevarse el dinero del equipo.',
  'Il nuovo finanziamento del laboratorio è la roulette. Almeno il casinò pubblica le probabilità prima di prendere i soldi per le attrezzature.',
  'نموذج تمويل المختبر الجديد هو الروليت. الكازينو على الأقل يعلن الاحتمالات قبل أخذ مال المعدات.')),
('Cheyenne', 'https://sos.wyo.gov/Media/2025/SoS_Release_2025-07-09.pdf', 'documented',
 ('In Cheyenne, Wyoming’s secretary of state publicly praised Trump’s July 2025 executive order aimed at ending federal subsidies for wind and solar energy.',
  'En Cheyenne, el secretario de Estado de Wyoming elogió públicamente el decreto de Trump de julio de 2025 destinado a terminar las ayudas federales a la energía eólica y solar.',
  'A Cheyenne, il segretario di stato del Wyoming elogiò il decreto di Trump del luglio 2025 volto a porre fine ai sussidi federali per eolico e solare.',
  'في شايان، أشاد أمين ولاية وايومنغ علناً بأمر ترامب التنفيذي في يوليو 2025 الهادف لإنهاء الدعم الفيدرالي لطاقة الرياح والشمس.'),
 ('We finally found a way to oppose both wind and sunshine. Wyoming’s weather has been referred to the loyalty committee.',
  'Por fin logramos oponernos al viento y al sol. El clima de Wyoming comparecerá ante el comité de lealtad.',
  'Finalmente ci opponiamo sia al vento sia al sole. Il meteo del Wyoming è stato deferito al comitato di lealtà.',
  'وجدنا أخيراً طريقة لمعارضة الرياح والشمس معاً. أُحيل طقس وايومنغ إلى لجنة الولاء.')),
('Las Vegas', 'https://apnews.com/article/fbcb23cacef7c54f4ecaac0a43ba0703', 'reported',
 ('In 2025, Las Vegas officials linked falling tourism partly to Trump’s tariffs and immigration policies; other economic pressures also mattered.',
  'En 2025, autoridades de Las Vegas vincularon parte de la caída turística a los aranceles y políticas migratorias de Trump; también influyeron factores económicos.',
  'Nel 2025 autorità di Las Vegas collegarono parte del calo turistico ai dazi e alle politiche migratorie di Trump, oltre ad altre pressioni economiche.',
  'في 2025 ربط مسؤولون في لاس فيغاس تراجع السياحة جزئياً برسوم ترامب وسياساته للهجرة، إلى جانب ضغوط اقتصادية أخرى.'),
 ('The house always wins. Unless the house insults the Canadians until they stop booking rooms.',
  'La casa siempre gana. Salvo si insulta a los canadienses hasta que dejan de reservar habitaciones.',
  'Il banco vince sempre. Tranne quando insulta i canadesi finché smettono di prenotare camere.',
  'الكازينو يفوز دائماً. إلا إذا أهان الكنديين حتى توقفوا عن حجز الغرف.')),
('Flagstaff', 'https://www.kjzz.org/text/the-show/2025-06-18/trump-proposal-would-almost-completely-cut-funds-for-grand-canyon-monitoring-and-research-center', 'proposed',
 ('A June 2025 KJZZ interview warned that Trump’s proposed USGS cuts could close Flagstaff’s Grand Canyon Monitoring and Research Center. This was a proposal, not a reported closure.',
  'Una entrevista de KJZZ de junio de 2025 advirtió que los recortes propuestos por Trump al USGS podrían cerrar el centro de investigación del Gran Cañón en Flagstaff; no era un cierre confirmado.',
  'Un’intervista KJZZ del giugno 2025 avvertì che i tagli USGS proposti da Trump potevano chiudere il centro di ricerca sul Grand Canyon a Flagstaff; non era una chiusura confermata.',
  'حذرت مقابلة KJZZ في يونيو 2025 من أن اقتطاعات ترامب المقترحة لـUSGS قد تغلق مركز أبحاث ومراقبة غراند كانيون في فلاغستاف. كان ذلك مقترحاً لا إغلاقاً مؤكداً.'),
 ('If we stop monitoring the canyon, perhaps nobody will notice the hole in the science budget.',
  'Si dejamos de vigilar el cañón, quizá nadie note el agujero en el presupuesto científico.',
  'Se smettiamo di monitorare il canyon, forse nessuno noterà il buco nel bilancio della ricerca.',
  'إن توقفنا عن مراقبة الوادي، ربما لا يلاحظ أحد الحفرة في ميزانية العلوم.')),
('Albuquerque', 'https://www.cabq.gov/mayor/news/trump-administration-attempts-to-cancel-money-for-rail-trail', 'documented',
 ('Albuquerque said the Trump administration tried to cancel its Rail Trail grant, awarded in 2022 through the federal RAISE program. The city challenged that effort.',
  'Albuquerque informó de que Trump intentó cancelar la subvención de su Rail Trail, concedida en 2022 por el programa federal RAISE. La ciudad impugnó la medida.',
  'Albuquerque riferì che l’amministrazione Trump aveva tentato di cancellare il finanziamento Rail Trail, assegnato nel 2022 dal programma federale RAISE. La città si oppose.',
  'قالت ألبوكيركي إن إدارة ترامب حاولت إلغاء منحة Rail Trail الممنوحة في 2022 عبر برنامج RAISE الفيدرالي. وطعنت المدينة في المحاولة.'),
 ('The grant was called RAISE. The administration appears to have installed the LOWER update.',
  'La subvención se llamaba RAISE: elevar. La administración parece haber instalado la actualización BAJAR.',
  'Il programma si chiamava RAISE: sollevare. L’amministrazione sembra aver installato l’aggiornamento ABBASSA.',
  'اسم المنحة RAISE، أي ارفع. يبدو أن الإدارة ثبتت تحديث «اخفض».')),
('Amarillo', 'https://media.texasfarmbureau.org/plan-to-import-argentinian-beef-harms-u-s-cattle-ranchers/', 'documented',
 ('Texas Farm Bureau objected in October 2025 to Trump’s suggestion of importing more Argentine beef to lower prices, warning that it could harm Texas ranchers.',
  'Texas Farm Bureau se opuso en octubre de 2025 a importar más carne argentina, como sugirió Trump para bajar precios, y advirtió del perjuicio para ganaderos texanos.',
  'Nell’ottobre 2025 Texas Farm Bureau contestò l’idea di Trump di importare più manzo argentino per abbassare i prezzi, avvertendo dei danni per gli allevatori texani.',
  'اعترض مكتب مزارع تكساس في أكتوبر 2025 على اقتراح ترامب استيراد مزيد من لحم البقر الأرجنتيني لخفض الأسعار، محذراً من ضرره بمربي الماشية في تكساس.'),
 ('America First beef has developed a surprising Argentine accent. Our cattle are checking their passports.',
  'La carne de «Estados Unidos primero» adquirió un sorprendente acento argentino. Nuestro ganado revisa sus pasaportes.',
  'Il manzo America First ha un sorprendente accento argentino. Il nostro bestiame controlla i passaporti.',
  'لحم «أمريكا أولاً» اكتسب لهجة أرجنتينية مفاجئة. ماشيتنا تفحص جوازات سفرها.')),
('Phoenix', 'https://www.azag.gov/press-release/attorney-general-mayes-safeguards-15-billion-federal-funds-arizona-lawsuits-against', 'documented',
 ('Arizona’s attorney general said in August 2025 that lawsuits against the Trump administration had protected $1.5 billion in federal funding while the cases continued.',
  'La fiscal general de Arizona afirmó en agosto de 2025 que las demandas contra Trump habían protegido 1.500 millones de dólares federales mientras continuaban los casos.',
  'Nell’agosto 2025 la procuratrice generale dell’Arizona dichiarò che le cause contro Trump avevano protetto 1,5 miliardi di dollari federali mentre i procedimenti proseguivano.',
  'قالت المدعية العامة لأريزونا في أغسطس 2025 إن الدعاوى ضد إدارة ترامب حمت تمويلاً فيدرالياً بقيمة 1.5 مليار دولار أثناء استمرار القضايا.'),
 ('Our strongest infrastructure is now the injunction. Unfortunately it provides very little shade.',
  'Nuestra infraestructura más sólida es ahora la orden judicial. Por desgracia, da muy poca sombra.',
  'La nostra infrastruttura più solida è ormai l’ingiunzione. Purtroppo fa pochissima ombra.',
  'أقوى بنيتنا التحتية الآن هو الأمر القضائي. للأسف لا يوفر إلا قليلاً من الظل.')),
('Tucson', 'https://www.tucsonaz.gov/files/sharedassets/public/v/1/bsd/documents/finance-documents/prior-budgets/april-22-2025-study-session.pdf', 'estimated',
 ('Tucson’s April 2025 budget briefing warned that grant-funded jobs could be at risk as Trump administration orders were issued and rescinded. The warning was conditional.',
  'El informe presupuestario de Tucson de abril de 2025 advirtió que empleos financiados con subvenciones podían peligrar ante decretos de Trump emitidos y retirados. Era una advertencia condicional.',
  'Il rapporto di bilancio di Tucson dell’aprile 2025 avvertì che i posti finanziati da sovvenzioni potevano essere a rischio mentre Trump emanava e revocava decreti. Era un rischio condizionato.',
  'حذر تقرير ميزانية توسان في أبريل 2025 من احتمال تهديد وظائف تمولها المنح، مع إصدار أوامر إدارة ترامب وسحبها. كان التحذير مشروطاً.'),
 ('We added a new budget column: depends what he posts before lunch. The spreadsheet has requested hazard pay.',
  'Añadimos una columna: depende de lo que publique antes de comer. La hoja de cálculo exige un plus de peligrosidad.',
  'Abbiamo aggiunto una colonna: dipende da cosa pubblica prima di pranzo. Il foglio di calcolo chiede l’indennità di rischio.',
  'أضفنا عمود ميزانية: يتوقف على ما ينشره قبل الغداء. جدول الحسابات يطالب ببدل مخاطر.')),
('El Paso', 'https://www.7atc.army.mil/Media-News/Video/videoid/963366/dvpTag/2nd/', 'documented',
 ('The Army documented soldiers patrolling a newly designated Texas National Defense Area near El Paso in May 2025, part of the Trump administration’s border militarization.',
  'El Ejército documentó patrullas en la nueva Área de Defensa Nacional de Texas cerca de El Paso en mayo de 2025, parte de la militarización fronteriza de Trump.',
  'L’esercito documentò pattuglie nella nuova Area di difesa nazionale del Texas vicino a El Paso nel maggio 2025, parte della militarizzazione del confine sotto Trump.',
  'وثق الجيش دوريات في منطقة الدفاع الوطني الجديدة بتكساس قرب إل باسو في مايو 2025، ضمن عسكرة الحدود في عهد ترامب.'),
 ('Chamizal celebrates solving a border dispute peacefully. Apparently that was the exhibit the administration skipped.',
  'Chamizal celebra resolver pacíficamente una disputa fronteriza. Parece que la administración se saltó esa exposición.',
  'Chamizal celebra una disputa di confine risolta pacificamente. Pare che l’amministrazione abbia saltato quella mostra.',
  'شاميزال يحتفي بحل نزاع حدودي سلمياً. يبدو أن الإدارة تجاوزت ذلك المعرض.')),
('San Antonio', 'https://www.mysanantonio.com/news/local/article/head-start-funding-federal-freeze-20061743.php', 'reported',
 ('Trump’s January 2025 funding freeze left San Antonio preschool providers seeking answers. SAISD said operations would continue while it awaited guidance.',
  'La congelación de Trump en enero de 2025 dejó a los preescolares de San Antonio buscando respuestas. SAISD mantuvo sus servicios mientras esperaba instrucciones.',
  'Il blocco dei fondi di Trump nel gennaio 2025 lasciò gli asili di San Antonio in cerca di risposte. SAISD mantenne i servizi in attesa di indicazioni.',
  'ترك تجميد تمويل ترامب في يناير 2025 برامج ما قبل المدرسة بسان أنطونيو تبحث عن إجابات. وأبقت SAISD خدماتها جارية بانتظار التوجيه.'),
 ('The children are learning object permanence. The adults are waiting to learn whether the grant still exists.',
  'Los niños aprenden que los objetos siguen existiendo. Los adultos esperan saber si la subvención también.',
  'I bambini imparano che gli oggetti continuano a esistere. Gli adulti aspettano di sapere se vale anche per il finanziamento.',
  'الأطفال يتعلمون أن الأشياء تظل موجودة. والكبار ينتظرون معرفة إن كان ذلك ينطبق على المنحة.')),
]
