// Real Safari via Apple's built-in WebDriver, with a disposable local origin.
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import assert from 'node:assert/strict';
const built=process.env.PLAYTEST_DIST||'/tmp/dystrail-continuity-preview/play';
const output=process.env.SAFARI_OUTPUT||'/tmp/dystrail-safari';mkdirSync(output,{recursive:true});
const driver='http://127.0.0.1:9515';
let session=process.env.SAFARI_SESSION;
async function call(path,body,method=body===undefined?'GET':'POST'){
 const r=await fetch(driver+path,{method,signal:AbortSignal.timeout(30000),headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json();if(!r.ok||d.value?.error)throw new Error(JSON.stringify(d.value));return d.value;
}
if(!session){const result=await call('/session',{capabilities:{alwaysMatch:{browserName:'safari'}}});session=result.sessionId;console.log('Safari',result.capabilities.browserVersion);}
const cmd=(path,body,method)=>call(`/session/${session}${path}`,body,method);
const exec=(script,args=[])=>cmd('/execute/sync',{script,args});
const asyncExec=(script,args=[])=>cmd('/execute/async',{script,args});
async function until(script,timeout=20000){const start=Date.now();while(Date.now()-start<timeout){try{if(await exec(script))return;}catch{}await new Promise(r=>setTimeout(r,200));}throw new Error('Timed out: '+script+'\n'+await exec('return document.body.innerText'));}
async function click(label){console.log('Click',label);await until('return [...document.querySelectorAll("button")].some(e=>e.offsetHeight&&!e.disabled&&(e.getAttribute("aria-label")==='+JSON.stringify(label)+'||e.textContent.trim()==='+JSON.stringify(label)+'))');const el=await exec('return [...document.querySelectorAll("button")].find(e=>e.offsetHeight&&!e.disabled&&(e.getAttribute("aria-label")===arguments[0]||e.textContent.trim()===arguments[0]));',[label]);assert(el,`Button: ${label}`);await exec('arguments[0].scrollIntoView({block:"center",behavior:"instant"});',[el]);await new Promise(r=>setTimeout(r,150));await cmd('/element/'+el['element-6066-11e4-a52e-4f735466cecf']+'/click',{});}
async function clickCSS(selector){const el=await cmd('/element',{using:'css selector',value:selector});await exec('arguments[0].scrollIntoView({block:"center",behavior:"instant"});',[el]);await new Promise(r=>setTimeout(r,150));await cmd('/element/'+el['element-6066-11e4-a52e-4f735466cecf']+'/click',{});}
async function fill(selector,text){if(text.length>500){await exec('const e=document.querySelector(arguments[0]);Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set.call(e,arguments[1]);e.dispatchEvent(new Event("input",{bubbles:true}));',[selector,text]);return;}const el=await cmd('/element',{using:'css selector',value:selector});const id=el['element-6066-11e4-a52e-4f735466cecf'];await cmd('/element/'+id+'/clear',{});await cmd('/element/'+id+'/value',{text});await until('return document.querySelector('+JSON.stringify(selector)+').value==='+JSON.stringify(text));}
async function menu(){if(!await exec('return document.querySelector("#game-menu-button").getAttribute("aria-expanded")==="true"'))await clickCSS('#game-menu-button');}
const state=()=>exec('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state');
async function weatherDetails(){assert.equal(await exec('return document.querySelectorAll(".weather-indicator .weather-impact").length'),0);await clickCSS('.weather-indicator .help-trigger');await until('return !!document.querySelector(".viewport-help .weather-details")');}
const weatherCost=key=>exec('return [...document.querySelectorAll(".viewport-help .weather-details [data-stat]")].find(e=>e.dataset.stat===arguments[0])?.querySelector("strong")?.textContent;',[key]);
async function importState(gs){await menu();await clickCSS('#save-open-btn');await clickCSS('.save-text-backup > summary');await until('return document.querySelector(".save-text-backup").open');await fill('#import-json',JSON.stringify(gs));await click('Import');await until('return !document.querySelector(".drawer")');}
async function shot(name){await asyncExec('Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))).then(()=>arguments[arguments.length-1](true));');writeFileSync(join(output,name+'.png'),Buffer.from(await cmd('/screenshot'),'base64'));assert(await exec('return document.documentElement.scrollWidth<=innerWidth'),name+' horizontal overflow');}
const html=readFileSync(join(built,'index.html'),'utf8');const original=JSON.parse(readFileSync(join(built,'offline-manifest.json'),'utf8'));const worker=readFileSync(join(process.env.PLAYTEST_SOURCE||'..','scripts/offline-worker.js'),'utf8');
let version='one',fail=false,hold=true,waiting=false,release=()=>{};
const updatedHtml=()=>html.replace('</head>',`<meta name="test-build" content="${version}"></head>`);
const build=()=>({...original,revision:original.revision+'-'+version,assets:original.assets.map(a=>a.path==='index.html'?{...a,bytes:Buffer.byteLength(updatedHtml()),integrity:'sha256-'+createHash('sha256').update(updatedHtml()).digest('base64')}:a)});
const server=createServer(async(req,res)=>{
 res.setHeader('Cache-Control','no-store');const path=new URL(req.url,'http://fixture').pathname.replace(/^\/play\//,'');
 if(path==='sw.js'){res.setHeader('Content-Type','text/javascript');res.end('const BUILD='+JSON.stringify(build())+';\n'+worker);return;}
 if(path==='static/img/journey/town-npcs-v1.png'){if(fail){res.statusCode=503;res.end('interrupted');return;}if(hold)await new Promise(resolve=>{release=resolve;waiting=true;});}
 const mime=path.endsWith('.js')?'text/javascript':path.endsWith('.wasm')?'application/wasm':path.endsWith('.css')?'text/css':path.endsWith('.webmanifest')?'application/manifest+json':path.endsWith('.png')?'image/png':path.endsWith('.svg')?'image/svg+xml':undefined;if(mime)res.setHeader('Content-Type',mime);
 if(path==='index.html'||!path||!path.includes('.')){res.setHeader('Content-Type','text/html');res.end(updatedHtml());return;}
 try{res.end(readFileSync(join(built,path)));}catch{res.statusCode=404;res.end();}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,origin=`http://127.0.0.1:${port}/play/`;
const checks=[];function pass(name){checks.push(name);console.log('PASS',name);writeFileSync(join(output,'validation.json'),JSON.stringify({browser:'Safari 26.6.2',origin,checks},null,2));}
try{
 await cmd('/timeouts',{script:40000,pageLoad:30000,implicit:0});await cmd('/window/rect',{width:1280,height:980});await cmd('/url',{url:origin});
 await until('return !!document.querySelector("#launch-gate")');assert.equal(await exec('return !!document.querySelector("#main")'),false);for(let i=0;!waiting&&i<100;i++)await new Promise(r=>setTimeout(r,100));assert(waiting);assert(await exec('return document.querySelector("#launch-progress").value>0'));await shot('first-download');hold=false;release();pass('First launch holds gameplay until every scene and game asset is cached');
 await cmd('/window',{handle:await cmd('/window')});
 assert.equal(await exec('return document.visibilityState'),'visible','Unlock the Mac and make the Safari test window visible before running native input checks');
 await until('return document.querySelector("#main") && localStorage.getItem("dystrail.autosave.v1")');
 assert.equal(await exec('return scrollY'),0);assert.notEqual(await exec('return document.activeElement?.id'),'main');
 const bootAlignment=await exec('const a=document.querySelectorAll(".mode-option")[1].getBoundingClientRect(),b=document.querySelector(".setup-start-row>button").getBoundingClientRect();return Math.abs(a.x-b.x);');assert(bootAlignment<1);await shot('setup-alignment');pass('Start button aligns with the Deep End column');
 await click('Choose your character');await until('return document.querySelectorAll(".persona-tile[aria-checked=true]").length===1');const firstCharacter=await exec('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).pending.persona_id');assert(firstCharacter);await cmd('/refresh',{});await until('return !!document.querySelector(".persona-select")');assert.equal(await exec('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).pending.persona_id'),firstCharacter);assert.equal(await exec('return document.activeElement.tagName'),'BODY');assert(!await exec('return document.querySelector("#persona-preview").textContent.includes("public hearing")'));await click('Whistleblower');const rowAlignment=await exec('const a=document.querySelector("#persona-helper").getBoundingClientRect(),b=document.querySelector("#persona-continue").getBoundingClientRect();return Math.abs(a.y+a.height/2-b.y-b.height/2);');assert(rowAlignment<1);await shot('character-details');pass('Random character is selected and persisted without focus jumps; mission and action alignment are correct');await exec('document.activeElement.blur()');await cmd('/actions',{actions:[{type:'key',id:'character-keys',actions:[{type:'keyDown',value:'1'},{type:'keyUp',value:'1'},{type:'keyDown',value:'\uE014'},{type:'keyUp',value:'\uE014'}]}]});await until('return document.activeElement?.textContent.trim()==="Organizer"');pass('Number-key character selection transfers focus so arrow navigation works');await click('Journalist');await click('Continue');await until('return document.querySelector("#crew-name")');
 await fill('#crew-name-journalist','River Safari');await fill('#crew-name','Safari Receipts');await shot('crew-desktop');
 const portraits=await exec('return [...document.querySelectorAll(".crew-portrait")].map(e=>({w:e.clientWidth,h:e.clientHeight,fit:getComputedStyle(e).objectFit,bg:getComputedStyle(e).backgroundColor,border:getComputedStyle(e).borderWidth}))');assert(portraits.every(p=>p.w>=54&&p.h>=64&&p.fit==='contain'&&p.bg==='rgba(0, 0, 0, 0)'&&p.border==='0px'));pass('Onboarding: names, compact transparent portraits, no focus jump');
 await click('Continue');await until('return document.querySelector(".loadout-panel")');assert((await exec('return document.querySelector(".loadout-panel").textContent')).includes('$71'));await click('Empty the van');await cmd('/refresh',{});await until('return document.querySelector(".loadout-panel")');assert.equal(await exec('return document.querySelectorAll(".store-item-selected").length'),0);pass('Paid starter cart can be emptied and persists across refresh');
 await click('Review & depart');await click('Start the journey');await until('return document.querySelector("#main").dataset.screen==="travel"');const gs=await state();assert.equal(gs.stats.supplies,0);assert.equal(gs.budget_cents,12000);pass('Empty departure has no hidden supplies or charges');
 await menu();await until('return document.querySelector(".offline-status")');
 const offlineGeometry=await exec('const e=document.querySelector(".offline-status"),b=e.querySelector(".offline-readiness .help-trigger"),r=b.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(b);const t=range.getBoundingClientRect();return {width:e.getBoundingClientRect().width,parent:e.parentElement.getBoundingClientRect().width,helpWidth:r.width,helpHeight:r.height,inset:Math.min(t.left-r.left,r.right-t.right,t.top-r.top,r.bottom-t.bottom)};');assert(Math.abs(offlineGeometry.width-offlineGeometry.parent)<2);assert.equal(offlineGeometry.helpWidth,28);assert.equal(offlineGeometry.helpHeight,28);assert(offlineGeometry.inset>=0);assert(await exec('const e=document.querySelector(".offline-status");return e.parentElement.lastElementChild===e && e.lastElementChild.classList.contains("offline-readiness");'));await shot('offline-menu');
 await click('How to install');await until('return document.querySelector(".viewport-help")');assert((await exec('return document.querySelector(".viewport-help").textContent')).includes('Add to Home Screen'));await shot('offline-install-help');await clickCSS('.wordmark');await menu();pass('Offline status spans the menu, help is centered, and labeled installation guidance opens correctly');await clickCSS('.wordmark');await until('return document.querySelector("#game-menu-button").getAttribute("aria-expanded")==="false"');pass('Menu dismisses when clicked outside');
 await clickCSS('.survival-hud .help-trigger');await until('return document.querySelector(".viewport-help")');const rect=await exec('const r=document.querySelector(".viewport-help").getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight};');assert(rect.left>=0&&rect.right<=rect.width&&rect.top>=0&&rect.bottom<=rect.height);await clickCSS('.wordmark');pass('Contextual help remains inside viewport and dismisses outside');
 await until('return window.dystrailOffline?.state==="ready"',40000);const manifest=await asyncExec('fetch("static/manifest.webmanifest").then(r=>r.json()).then(arguments[arguments.length-1])');assert.equal(manifest.display,'standalone');assert.equal(manifest.name,'Dystopian Trail');assert(await exec('return !!document.querySelector("link[rel=apple-touch-icon]")'));pass('Safari manifest and Apple touch icon available; complete offline cache ready');
 const actionRows=await exec('return [...document.querySelectorAll(".journey-actions>button")].map(e=>e.getBoundingClientRect().top)');assert.equal(actionRows.length,4);assert(Math.max(...actionRows)-Math.min(...actionRows)<2);assert.equal(await exec('return document.querySelectorAll(".travel-command").length'),0);assert(await exec('return document.querySelector(".journey-scene").getBoundingClientRect().height>=440'));pass('Fast, Camp, Route and Travel share one row with detail controls in the same toolbar');
 assert.deepEqual(await exec('return [...document.querySelectorAll(".journey-controls .travel-tabs button")].map(e=>e.textContent)'),['The Trail','Conditions','The Van','Journal']);
 assert.equal(await exec('return document.querySelectorAll(".speed-controls,.travel-controls .travel-tabs").length'),0);
 await click('Fast');assert.equal(await exec('return document.querySelector(".fast-mode-toggle").getAttribute("aria-checked")'),'true');await cmd('/refresh',{});await until('return document.querySelector(".fast-mode-toggle")?.getAttribute("aria-checked")==="true"');assert.equal(await exec('return getComputedStyle(document.querySelector(".travel-screen")).getPropertyValue("--travel-duration")'),'900ms');
 await click('Conditions');assert(await exec('return !!document.querySelector(".daily-settings")'));await click('The Van');assert(await exec('return !!document.querySelector(".van-crew")'));await click('Journal');assert(await exec('return !!document.querySelector(".trail-log")'));await click('The Trail');assert(!await exec('return !!document.querySelector(".trail-log")'));assert.deepEqual((await state()).stats,gs.stats);
 await exec('const s=JSON.parse(localStorage.getItem("dystrail.autosave.v1"));s.travel_speed="Step";localStorage.setItem("dystrail.autosave.v1",JSON.stringify(s));');await cmd('/refresh',{});await until('return document.querySelector(".fast-mode-toggle")?.getAttribute("aria-checked")==="false"');assert.equal(await exec('return getComputedStyle(document.querySelector(".travel-screen")).getPropertyValue("--travel-duration")'),'2600ms');assert.deepEqual((await state()).stats,gs.stats);pass('Fast toggle persists, detail panels switch without spending a turn, and old Step saves restore as Normal');
 assert.equal(await exec('return document.querySelectorAll(".service-icon").length'),0);await shot('travel-desktop');
 const sceneGeometry=await exec('const a=document.querySelector(".journey-scene").getBoundingClientRect(),h=document.querySelector(".resource-hud").getBoundingClientRect();return {top:a.top-h.bottom,widths:[...document.querySelectorAll(".journey-actions>button")].map(e=>e.getBoundingClientRect().width)};');assert(Math.abs(sceneGeometry.top)<1);assert(Math.max(...sceneGeometry.widths)-Math.min(...sceneGeometry.widths)<1);assert.equal(await exec('return document.querySelectorAll(".scene-status,.leg-turn").length'),0);assert(await exec('return [".leg-destination",".leg-cash",".leg-vehicle"].every(s=>!!document.querySelector(".conditions-hud "+s))'));assert(!await exec('return !!document.querySelector(".journey-scene .critical-stats")'));pass('Resources sit above the art; destination, cash and vehicle use the top HUD, with no bottom turn bar and matching action widths');
 await click('Conditions');assert(!await exec('return !!document.querySelector(".turn-receipt")'));await click('The Trail');assert(await exec('return !!document.querySelector(".turn-receipt")'));pass('The Trail is its own tab and does not intrude into Conditions, The Van, or Journal');
 await menu();await click('Help & tips');assert.equal(await exec('return [...document.querySelectorAll("[data-help-kind=tip]")].filter(e=>getComputedStyle(e).visibility!=="hidden"&&getComputedStyle(e).display!=="none").length'),0);assert(await exec('return document.querySelectorAll("[data-help-kind=info]").length>0'));await cmd('/refresh',{});await until('return !!document.querySelector("#main")');assert.equal(await exec('return [...document.querySelectorAll("[data-help-kind=tip]")].filter(e=>getComputedStyle(e).visibility!=="hidden"&&getComputedStyle(e).display!=="none").length'),0);await clickCSS('.weather-indicator button');await until('return !!document.querySelector(".viewport-help")');await clickCSS('.wordmark');await menu();await click('Help & tips');await clickCSS('.wordmark');assert(await exec('return [...document.querySelectorAll("[data-help-kind=tip]")].filter(e=>getComputedStyle(e).visibility!=="hidden"&&getComputedStyle(e).display!=="none").length>0'));pass('Help preference persists across reload; weather information remains usable when tips are off');


 await menu();await clickCSS('.language-picker>button');await click('العربية');await until('return document.documentElement.dir==="rtl"');assert((await exec('return document.querySelector(".offline-status").textContent')).includes('كيفية التثبيت'));await cmd('/refresh',{});await until('return document.documentElement.lang==="ar"&&!!document.querySelector("#main")');await shot('arabic-desktop');await menu();await clickCSS('.language-picker>button');await click('English');await until('return document.documentElement.lang==="en"');await clickCSS('.wordmark');pass('Arabic layout and selected language survive reload');
 const beforeManual=await state();await click('Route');await until('return document.querySelector(".map-scene")');const map=await exec('return document.querySelector(".us-route-map").getAttribute("viewBox")');assert(map&&Number(map.split(' ')[2])<1000);await shot('route-map');await new Promise(r=>setTimeout(r,5100));assert(await exec('return !!document.querySelector(".map-scene")'));await click('Close map');assert(!await exec('return [...document.querySelectorAll("button")].some(e=>e.textContent.trim()==="Pause travel")'));const afterManual=await state();assert.deepEqual(afterManual.stats,beforeManual.stats);assert.deepEqual(afterManual.journal,beforeManual.journal);assert.equal(afterManual.clock_minutes,beforeManual.clock_minutes);assert.equal(afterManual.miles_traveled_actual,beforeManual.miles_traveled_actual);await click('Travel');await until('return [...document.querySelectorAll("button")].some(e=>e.textContent.trim()==="Pause travel")');await click('Pause travel');await until('return document.querySelector("#main").dataset.screen!=="traveling"');pass('Geographic map frames the active route as a full scene');
 const touring=structuredClone(gs);touring.day=6;touring.seed=42;touring.rng_bundle=null;touring.encounter_cooldown=100;touring.encounter_chance_today=0;touring.weather_state.neutral_buffer=100;touring.day_state.day_initialized=true;touring.crew_care.last_check_day=100;touring.stats={...touring.stats,supplies:20,sanity:10,hp:10,morale:10,pants:0};touring.route_services.map_reviewed=null;
 await importState(touring);await click('Travel');await until('return !!document.querySelector(".map-countdown")');const mapStart=await state();await shot('automatic-map');await until('return !document.querySelector(".map-scene")',4000);assert((await state()).journal.length>mapStart.journal.length);await click('Pause travel');await until('return document.querySelector("#main").dataset.screen!=="traveling"');assert((await state()).route_services.map_reviewed);pass('Automatic map travels in the background, closes within the three-second countdown, and needs no extra Resume click');
 await importState(touring);await click('Travel');await until('return !!document.querySelector(".map-countdown")');await click('Stay on map');await new Promise(r=>setTimeout(r,3000));const parked=await state();await new Promise(r=>setTimeout(r,3000));assert.deepEqual((await state()).journal,parked.journal);await cmd('/refresh',{});await until('return !!document.querySelector(".map-scene")');assert(!await exec('return !!document.querySelector(".map-countdown")'));await click('Resume travel');await until('return !!document.querySelector(".transit-caption")');await click('Pause travel');await until('return document.querySelector("#main").dataset.screen!=="traveling"');pass('Stay on map cancels automatic closing and travel, persists on reload, and resumes with one click');
 await importState(touring);await click('Fast');assert.equal(await exec('return document.querySelector(".fast-mode-toggle").getAttribute("aria-checked")'),'true');await exec('window.safariUnexpectedMap=false;window.safariMapObserver=new MutationObserver(()=>{if(document.querySelector(".map-scene"))window.safariUnexpectedMap=true;});window.safariMapObserver.observe(document,{childList:true,subtree:true});');await click('Travel');await until('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.journal.length>'+String(touring.journal.length));await click('Pause travel');await until('return document.querySelector("#main").dataset.screen!=="traveling"');assert.equal(await exec('return window.safariUnexpectedMap'),false);await exec('window.safariMapObserver.disconnect()');assert.equal(await exec('return document.querySelectorAll(".map-scene").length'),0);await click('Fast');pass('Fast mode never automatically opens the route map during travel');
 for(const [weather,effect]of [['HeatWave','heat'],['ColdSnap','cold']]){const w=structuredClone(gs);w.weather_state.today=weather;await importState(w);assert.equal(await exec('return document.querySelector(".journey-scene").dataset.weather'),effect);await shot(weather);}pass('Heat and cold use state-matched effects in Safari');
 const changing=structuredClone(gs);changing.seed=5;changing.rng_bundle=null;changing.encounter_cooldown=100;changing.encounter_chance_today=0;changing.day_state.day_initialized=false;changing.weather_impact=null;changing.stats={...changing.stats,supplies:20,hp:10,sanity:10,morale:10,pants:0};changing.inventory.tags=['water_jugs'];changing.weather_state={today:'Clear',yesterday:'Clear',extreme_streak:0,heatwave_streak:0,coldsnap_streak:0,neutral_buffer:0};
 changing.region='Heartland';await importState(changing);const count=changing.journal.length;await click('Travel');
 await until('return !!JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.weather_impact');const charged=await state();assert.notEqual(charged.weather_state.today,'Clear');await until('return document.querySelector(".weather-indicator")?.dataset.weather==='+JSON.stringify(charged.weather_state.today));assert(await exec('return document.querySelector(".weather-indicator").classList.contains("weather-changed")'));await weatherDetails();assert.equal(await weatherCost('ux.supplies'),'-1');await clickCSS('.viewport-help .help-dismiss');assert(!await exec('return !!document.querySelector(".weather-notice")'));
 await until('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.journal.length>='+String(count+2));await click('Pause travel');await until('return document.querySelector("#main").dataset.screen!=="traveling"');const weatherSaved=await state();await cmd('/refresh',{});await until('return !!document.querySelector(".weather-indicator")');assert.deepEqual((await state()).stats,weatherSaved.stats);assert.deepEqual((await state()).journal,weatherSaved.journal);await shot('weather-continuous');pass('Weather applies real costs and notifies inline while travel continues; reload never repeats costs');
 const exposure=structuredClone(gs);exposure.weather_state.today='HeatWave';exposure.weather_impact={day:gs.day,weather:'HeatWave',supplies:-1,hp:-1,sanity:-2,pants:1};await importState(exposure);await weatherDetails();assert.equal(await weatherCost('ux.health'),'-1');assert.equal(await weatherCost('ux.sanity'),'-2');assert((await exec('return document.querySelector(".viewport-help").textContent')).includes('after gear protection'));await clickCSS('.viewport-help .help-dismiss');await shot('weather-exposure');await importState(gs);const clearWeather=await state();await weatherDetails();assert.equal(await exec('return document.querySelector(".viewport-help .weather-details section p").textContent'),clearWeather.weather_impact?.weather===clearWeather.weather_state.today?'No weather cost':'No weather cost recorded yet.');assert.equal(await exec('return document.querySelector(".viewport-help .weather-details section").querySelectorAll("[data-stat]").length'),0);await clickCSS('.viewport-help .help-dismiss');assert.deepEqual((await state()).stats,gs.stats);pass('Weather information shows exposure and clears obsolete damage in clear conditions without charging resources');
 await importState(gs);await click('Camp');await click('Forage with a local guide');await until('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.stats.supplies===2');assert.equal((await state()).clock_minutes,gs.clock_minutes+120);await click('Continue');await until('return !!document.querySelector(".camp-gather")');assert.equal(await exec('return document.querySelectorAll(".camp-action").length'),3);assert.deepEqual(await exec('return [...document.querySelectorAll(".camp-actions button[aria-label]")].map(e=>e.getAttribute("aria-label"))'),['Rest','Forage with a local guide','Help glean a nearby farm']);assert(await exec('return document.querySelector(".camp-gather button").disabled'));assert((await exec('return document.querySelector(".camp-gather .cooldown-status").textContent')).includes('3 travel days'));await shot('camp-cooldowns');pass('Camp gathering applies costs, returns to camp, and displays persisted cooldown cards');
 const broken=structuredClone(gs);broken.breakdown={part:'Alternator',day_started:gs.day};broken.budget_cents=0;broken.stats.sanity=6;broken.stats.morale=6;broken.clock_minutes=1380;broken.vehicle.health=60;await importState(broken);const disabled=await exec('return [...document.querySelectorAll(".action-option button")].slice(0,3).every(b=>b.disabled)');assert(disabled);await click('Call local radio; work in exchange for repairs');await until('return !JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.breakdown');const repaired=await state();assert.equal(repaired.clock_minutes,720);assert.equal(repaired.clock_minutes-480,240);assert.equal(repaired.driving_minutes_total,broken.driving_minutes_total);assert.equal(repaired.miles_traveled_actual,broken.miles_traveled_actual);assert.equal(repaired.budget_cents,0);assert.equal(repaired.day,gs.day+1);assert.equal(repaired.stats.sanity,6);assert.equal(repaired.stats.morale,5);assert(await exec('const r=document.querySelector("#outcome-continue").getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;'));pass('Repair outcomes keep return controls reachable and charge four active hours, sanity and morale without driving');
 const critical=structuredClone(gs);critical.stats.sanity=2;await importState(critical);assert(!await exec('return !!document.querySelector(".danger-notice")'));assert.equal(await exec('return getComputedStyle(document.querySelector(".hud-stat.critical")).animationIterationCount'),'3');pass('Critical sanity uses the stat warning and three-second pulse without a popup');
 const event=structuredClone(gs);event.current_encounter=JSON.parse(readFileSync(join(built,'static/assets/data/game.json'),'utf8')).find(e=>e.id==='sat_corn_bullets');await importState(event);assert.equal(await exec('return document.querySelector(".journey-scene").dataset.scene'),'enc-farm-office');assert.equal(await exec('return document.querySelector(".scene-atlas").dataset.atlas'),'encounter-settings-v3');assert.equal(await exec('return document.querySelector(".scene-atlas").dataset.cell'),'4');await clickCSS('.wordmark');await cmd('/actions',{actions:[{type:'key',id:'keyboard',actions:[{type:'keyDown',value:'2'},{type:'keyUp',value:'2'}]}]});await until('return JSON.parse(localStorage.getItem("dystrail.autosave.v1")).state.budget_cents==='+String(gs.budget_cents+800));await shot('paid-encounter');pass('Number keys select encounter choices; cash reward and matching scene agree');
 const routes=JSON.parse(readFileSync('../dystrail-game/data/routes.json','utf8'));const stop=routes.find(r=>r.id==='journalist').stops.find(s=>s.name==='Madison');gs.stats.supplies=12;gs.miles_traveled_actual=(stop.mile+1)/routes.find(r=>r.id==='journalist').total_miles*gs.trail_distance;gs.miles_traveled=Math.round(gs.miles_traveled_actual);gs.prev_miles_traveled=gs.miles_traveled_actual;gs.route_services={route_id:'journalist',stop:stop.mile,traded_at:null,talked_at:null,map_reviewed:null};gs.activities.local_word=null;await importState(gs);await until('return document.querySelector(".town-arrival")');
 const talk=await exec('return [...document.querySelectorAll("button")].find(e=>e.textContent.startsWith("Talk to locals")).textContent');await click(talk);await until('return document.querySelector(".local-fact")');assert((await exec('return document.querySelector(".local-fact").textContent')).includes('UW–Madison'));const npc=await exec('return document.querySelector(".scene-npc").dataset.npc');await cmd('/refresh',{});await until('return document.querySelector(".scene-npc")');assert.equal(await exec('return document.querySelector(".scene-npc").dataset.npc'),npc);await shot('town-desktop');pass('Exact-town fact, player portrait, random NPC and conversation persist');
 // Stop the only game origin completely. No browser network emulation or external API is involved.
 const saved=await state();server.closeAllConnections();await new Promise(r=>server.close(r));await cmd('/url',{url:origin+'town'});await until('return document.querySelector(".local-fact")');assert.deepEqual((await state()).party,saved.party);assert.deepEqual((await state()).stats,saved.stats);assert.deepEqual((await state()).journal,saved.journal);assert.equal((await state()).clock_minutes,saved.clock_minutes);
 const errors=await asyncExec('const done=arguments[arguments.length-1],assets=arguments[0];Promise.all(assets.map(async a=>{try{const r=await fetch(new URL(a.path,document.baseURI));return r.ok&&(await r.arrayBuffer()).byteLength===a.bytes?null:a.path;}catch{return a.path;}})).then(r=>done(r.filter(Boolean)));',[build().assets]);assert.deepEqual(errors,[]);await shot('offline-town');pass('Origin stopped: reload, saved crew, town scene and every bundled asset still work');
 await new Promise(r=>server.listen(port,'127.0.0.1',r));version='two';hold=true;const refreshing=cmd('/refresh',{});await until('return !!document.querySelector("#launch-gate")');assert.equal(await exec('return !!document.querySelector("#main")'),false);for(let i=0;!waiting&&i<100;i++)await new Promise(r=>setTimeout(r,100));assert(waiting);await shot('update-gate');hold=false;release();await refreshing;await until('return document.querySelector("meta[name=test-build]").content==="two" && !!document.querySelector("#main")',40000);assert.deepEqual((await state()).party,saved.party);pass('Complete update replaces old build before game launches and preserves saves');
 version='three';fail=true;await cmd('/refresh',{});await until('return !!document.querySelector("#main")');assert.equal(await exec('return document.querySelector("meta[name=test-build]").content'),'two');assert.deepEqual((await state()).party,saved.party);pass('Interrupted update leaves the last complete version playable');
 await click('Back to town');await menu();await click('Abandon trail');await click('End this journey');await until('return document.querySelector(".result-art-caption")');assert((await exec('return document.querySelector(".result-art-caption").textContent')).includes('River Safari'));await shot('ending-desktop');pass('Abandon uses the selected character’s name and creates a saved ending');

 const illness=structuredClone(gs);illness.persona_id='whistleblower';illness.party.members.find(m=>m.persona==='whistleblower').name='Willow Safari';illness.party.members.find(m=>m.persona==='whistleblower').status='Dead';illness.day=37;illness.clock_minutes=540;illness.trail_distance=2400;illness.miles_traveled_actual=501.7949;illness.miles_traveled=502;illness.ending={type:'collapse',cause:'disease'};illness.stats.sanity=0;illness.route_services={...illness.route_services,route_id:'whistleblower',stop:null};
 await importState(illness);await until('return document.querySelector("#result-title")?.textContent==="ILLNESS ENDS THE JOURNEY"');assert((await exec('return document.querySelector(".result-location").textContent')).includes('Reno → Salt Lake City'));assert((await exec('return document.querySelector(".result-location").textContent')).includes('21%'));assert((await exec('return document.querySelector(".result-art .result-profile").textContent')).includes('Willow Safari'));assert.equal(await exec('return document.querySelector(".result-art .journey-scene").dataset.scene'),'ending-rest-area');assert(!await exec('return !!document.querySelector(".result-art .scene-speaker,details.ending-scorecard")'));await exec('scrollTo(0,0)');await shot('illness-ending');pass('Early illness result uses the real route location, full scorecard and player identity, not a D.C. arrival or another crew member');
 const copyButton=await cmd('/element',{using:'css selector',value:'.result-menu [data-index="5"]'});await exec('arguments[0].scrollIntoView({block:"center",behavior:"instant"});',[copyButton]);const resultPosition=await exec('return {y:scrollY,h:document.querySelector(".game-header").getBoundingClientRect().height};');await cmd('/element/'+copyButton['element-6066-11e4-a52e-4f735466cecf']+'/click',{});await until('return [...document.querySelectorAll(".action-feedback")].some(e=>e.textContent==="Game export copied to clipboard.")');assert.equal(await exec('return scrollY'),resultPosition.y);assert.equal(await exec('return document.querySelector(".game-header").getBoundingClientRect().height'),resultPosition.h);assert(await exec('const e=[...document.querySelectorAll(".action-feedback")].find(e=>e.textContent==="Game export copied to clipboard."),r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;'));await shot('result-export-feedback');pass('Bottom result export stays in place and confirms the action inside the viewport');
 illness.party.members.find(m=>m.persona==='whistleblower').name='Reese Safari';illness.abandoned=true;await importState(illness);await until('return document.querySelector("#result-title")?.textContent==="The trail ends here"');assert((await exec('return document.querySelector(".result-profile").textContent')).includes('Reese Safari'));pass('Importing a different ending on the same day refreshes the result and player card');
 console.log('Safari completed:',checks.length,'checks');
}catch(error){try{await shot('failure');writeFileSync(join(output,'failure.txt'),await exec('return document.body.innerText'));}catch{}throw error;}
finally{release();await cmd('',undefined,'DELETE').catch(()=>{});server.closeAllConnections();await new Promise(r=>server.close(r));}
